version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
  postgres:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    networks:
      - internal
    environment:
      -  POSTGRES_USER=1200517
      -  POSTGRES_PASSWORD=1200517 
    ports:
      -  '5432:5432'

networks:
  internal:
    driver: bridge